// vue_list/src/App.vue
<script setup>
import { ref, onMounted } from "vue";

// reactive state
let wordPressGraphQL = ref("https://patrickdoran.com/headless/graphql")
let entries = ref([]);

const getPosts = (async () =>{
 // Queries Headless WordPress site configured for GraphQL
  const res = await fetch(wordPressGraphQL.value, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: `
        {				
          posts(where: {categoryName: "Speaking"}) {
            edges {
            node {
              excerpt
              date
              postId
              title
              content
            }
            }
          }
        }
      `,
    }),
  });

  // Wait for the results to load
  let results = await res.json();
  // Update Vue state
  return results.data.posts.edges;
})

// When the component is mounted, update state with the 
// headless Wordpress GraphQL post data
onMounted(async () => {
  entries.value = await getPosts()
});
</script>

<template>
  <div>
    <ul v-for="entry in entries" :key="entry.node.postId">
      <li>
        <p>{{ entry.node.title }}</p>
        <p>{{entry.node.excerpt }}</p>
        <p>{{ entry.node.content }}</p>
        <p><time datetime={entry.node.date}>{{entry.node.date.substring(0, 4)}}</time></p>
        </li>
    </ul>
  </div>
</template>

// react_timeline/src/App.js
import React, {useState ,useEffect} from 'react';

// GraphQL endpoint and query:
const wordPressGraphQL = 'https://patrickdoran.com/headless/graphql'
const wordPressGraphQLquery = `{
  posts(first:50, where: {categoryName: "Timeline", orderby: {field: DATE, order: ASC}}) {
    edges {
      node {
        date
        postId
        title
      }
    }
  }
}`;

// Component for an individual timeline entry
const PatrickDoranTimelineEntry = (props)=>{
  return (
        <div className='timeline__content'>
          <strong><time dateTime={props.entryDate}>{props.entryDate}</time></strong>
          <p><em>{props.entryTitle}</em></p>
        </div>
  )
}

function App() {

  const [isLoading, setIsLoading] = useState();
  const [results, setResults] = useState([]);

  useEffect(() => {
    function loadData(){

      setIsLoading(true)

      fetch(wordPressGraphQL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          query:wordPressGraphQLquery,
        })
      })
        .then(response => response.json())
        .then(data => {
          let results = data.data.posts.edges
          setResults(results)
          setIsLoading(false)
        })
        .catch((error) => {
          console.error('Error loading data via Wordpress GraphQL plugin: ', error);
        })
    }
    loadData()
  },[]);


  if (isLoading) {
    return <p>Loading Timeline ...</p>;
  }

  return (
    <div className="reactTimeline">
      <p>Timeline has loaaded! {isLoading}</p>

      {results.map(result =>
              <div className='timeline__item' key={result.node.postId}>
                  <PatrickDoranTimelineEntry 
                    entryTitle={result.node.title} 
                    entryDate={result.node.date.substr(0,4)} 
                  />
              </div>
            )}
    </div>
  );
}

export default App;
