// svelte_list/src/App.svelte
<script>
import { onMount } from 'svelte';
let wordPressGraphQL = 'https://patrickdoran.com/headless/graphql'
let items = [];
let filteredItems = [];

onMount(async () => {
// Queries Headless WordPress site configured for GraphQL
	const res = await fetch(wordPressGraphQL, {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify({
			query: `
				{				
					posts(where: {categoryName: "Speaking Writing"}) {
						edges {
						node {
							excerpt
							date
							postId
							title
							content
						}
						}
					}
				}
			`,
		}),
	})

	let graphQLresults = await res.json()

	items = graphQLresults.data.posts.edges;

	
	let mappedItems = items.map(x => {
	// Remove Wordpress markup from GraphQL 
		x.node.excerpt = x.node.excerpt.replace( /(<([^>]+)>)/ig, '');
		x.node.content = x.node.content.replace( /(<([^>]+)>)/ig, '');
		filteredItems.push(x.node)
	})
});
</script>

{#each items as listitem}
<li> 
	<a href={listitem.node.excerpt} target="_blank" rel="noreferrer">
	<header>{listitem.node.content.substring(0,3)}</header>
	<h3>{listitem.node.content.slice(3)}</h3>
		<span>{listitem.node.title}</span>
	</a>
	<time datetime={listitem.node.date}>{listitem.node.date.substring(0, 4)}</time>
</li>

{:else}
<li>Loading GraphQL data from a headless WordPress site into a Svelte component...</li>
{/each}

// vue_list/src/App.vue
<script setup>
import { ref, onMounted } from "vue";

// reactive state
let wordPressGraphQL = ref("https://patrickdoran.com/headless/graphql");
let entries = ref([]);

const getPosts = async () => {
  // Queries Headless WordPress site configured for GraphQL
  const res = await fetch(wordPressGraphQL.value, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: `
        {				
          posts(where: {categoryName: "Speaking"}) {
            edges {
            node {
              excerpt
              date
              postId
              title
              content
            }
            }
          }
        }
      `,
    }),
  });

  // Wait for the results to load
  let results = await res.json();

  // Update Vue state
  return results.data.posts.edges;
};

// When the component is mounted, update state with the
// headless Wordpress GraphQL post data
onMounted(async () => {
  entries.value = await getPosts();
});
</script>

<template>
  <ul>
    <li v-for="entry in entries" :key="entry.node.postId">
      <p>{{ entry.node.title }}</p>
      <p>{{ entry.node.excerpt.replace(/(<([^>]+)>)/gi, "") }}</p>
      <p>{{ entry.node.content.replace(/(<([^>]+)>)/gi, "") }}</p>
      <p>
        <time datetime="{entry.node.date}">{{
          entry.node.date.substring(0, 4)
        }}</time>
      </p>
    </li>
  </ul>
</template>
